### ISSUE TITLE
Returning future from with_ctx

### ISSUE THREAD

**Issue by Freyskeyd** [Diggsey/actix-interop#4]
Hello!

I was using `with_ctx` to call actor's state field and execute method that return futures. It was working with actix 0.9 and actix-interop 0.1.1 but it seems to not working anymore with actix 0.10 and master branch of actix-interop.

```rust
async move {
	match with_ctx(|actor: &mut Self, _| actor.storage.read(version, limit)).await {
		Ok(..) => ..,
		_ => ...
	}
}
.into_actor_boxed(self);

```
I Got some error like this one:

```
55 |                 with_ctx(|actor: &mut Self, _| actor.storage.read(version, limit));
   |                                  -           - ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ returning this value requires that `'1` must outlive `'2`
   |                                  |           |
   |                                  |           return type of closure is Pin<Box<(dyn futures::Future<Output = std::result::Result<Vec<Elem>, StorageError>> + std::marker::Send + '2)>>
   |                                  let's call the lifetime of this reference `'1`
```

Do you know a workaround or anything that can help? thank's !

**Comment by Diggsey** [comment]
I don't believe this is caused by a change in either actix-interop or actix. The issue is that the future returned by `actor.storage.read(...)` borrows `self`.

I don't know what the type of `storage.read()` is, but presumably in a previous version it returned a `Future + 'static`, and now it returns a `Future + 'a`, where `'a` is bound to the lifetime of `self`.

Unfortunately the only workaround for this is to make `read()` return a `'static` future again: the actix design does not allow polling futures which borrow from the actor state.

If you are interested in an actor system which does allow that, and generally has better async/await interop, you can try my `act-zero` crate.

**Comment by Freyskeyd** [comment]
Thank's.

I saw another crate using the same things as me here:

https://github.com/dmm/exopticon/blob/efb1d3658a22c8252a6ce269ed50c37bd8c87fb4/exopticon/src/telegram_actor.rs#L82

using the method of this crate: https://github.com/telegram-rs/telegram-bot/blob/master/lib/src/api.rs#L161

`read()` as this kind of definition:

```rust

    async fn read(
        &self,
        version: usize,
        limit: usize,
    ) -> Result<Vec<Elem>, StorageError>;
```

I'm wondering if it's not because of `async_trait` which I forgot to mention...

**Comment by Diggsey** [comment]
`async_trait` just mimics the signature that a standalone `async fn` would have. The issue is that `async fn` desugars to something different than what you see here: https://docs.rs/telegram-bot/0.8.0/telegram_bot/struct.Api.html#method.send

Signature of send:
```rust
pub fn send<Req: Request>(
    &self,
    request: Req,
) -> impl Future<Output = Result<<Req::Response as ResponseType>::Type, Error>> + Send
```

Signature of send if it was written as an async fn:
```rust
pub fn send<'a, Req: Request>(
    &'a self,
    request: Req,
) -> impl Future<Output = Result<<Req::Response as ResponseType>::Type, Error>> + Send + 'a
```

**Comment by Freyskeyd** [comment]
Oh ok!

So I tried to remove `async_trait` and did some refacto but I think I hitted a point that I don't understand.

My future panics with `cannot access a scoped thread local variable without calling `set` first`.

Does it occur because I'm using multiple `with_ctx` in different actor?
